name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: EC2にSSH接続してデプロイ
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            cd dashboard
            git pull origin main
            docker-compose up --build -d
